module.exports = {
  'qunit': 'QUnit',
  'module': 'module',
  'logReporter': 'log',
  'beginReporter': 'begin',
  'doneReporter': 'done',
  'logReporter': 'log',
  'moduleDoneReporter': 'moduleDone',
  'moduleStartReporter': 'moduleStart',
  'testDoneReporter': 'testDone',
  'testStartReporter': 'testStart',
  'moduleSetup': 'setup',
  'moduleTeardown': 'teardown',
  'moduleBeforeEach': 'beforeEach',
  'moduleAfterEach': 'afterEach',
  'assert': 'assert',
  'test': 'test',
  'assertPush': 'push',
  'thisObject': 'this',
  'okAssertion':'ok',
  'notOkAssertion': 'notOk',
  'equalAssertion': 'equal',
  'notEqualAssertion': 'notEqual',
  'strictEqualAssertion': 'strictEqual',
  'notStrictEqualAssertion': 'notStrictEqual',
  'deepEqualAssertion': 'deepEqual',
  'notDeepEqualAssertion': 'notDeepEqual',
  'propEqualAssertion': 'propEqual',
  'notPropEqualAssertion': 'notPropEqual',
  'throwsAssertion': 'throws',
  'raisesAssertion': 'raises',
  'expectAssertion': 'expect'
};
